### ISSUE TITLE
Compatibility with BizTalk 2016

### ISSUE THREAD

**Issue by AasthaKapoor** [wmmihaa/BizTalk-Benchmark-Wizard#1]
Hello,

I want to know if the tool is compatible with BizTalk Benchmark Wizard 2016.
When I try to execute it on my environment, the following error is logged in the eventlog:

Log Name:      Application
Source:        LoadGen
Date:          10-05-2017 14:56:53
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BRNCLUSBX1201.bestcorp.net
Description:
WCFTransport encountered an exception System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ClientFramingDuplexSessionChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at WcfTransport.IChannelAsyncNonTransactional.EndSend(IAsyncResult result)
   at WcfTransport.WcfClientAsyncNonTransactional.CallbackMethod(IAsyncResult asyncResult)
, Message No = 211

**Comment by wmmihaa** [comment]
It should work 😉

The exception “WCFTransport encountered an exception System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ClientFramingDuplexSessionChannel, cannot be used for communication because it is in the Faulted state” indicates that one of Loadgen’s clientd (used to call BizTalk) has faulted. This can happen for a number of reasons, but most commonly because it has timed out or being revoked. It can further indicate that your environment can’t handle the load.

Are you getting any messages through? If not, I suggest you try calling the endpoint from a custom client to make sure the receive location is accepting calls.

Cheers
Mikael
